In [8]:
people = {
    "first" : ["Jacob","Jane","John","Mary"],
    "last" : ["Xi","Doe","Wick","Doe"],
    "email" : ["jacobxi@outlook.com","JaneDone@outlook.com", "JohnWick@outlook.com","MD@outllok.com"]
}

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame(people)

In [11]:
df.sort_values(by='last')

   first  last                 email
1   Jane   Doe  JaneDone@outlook.com
3   Mary   Doe        MD@outllok.com
2   John  Wick  JohnWick@outlook.com
0  Jacob    Xi   jacobxi@outlook.com

In [12]:
df.sort_values(by='last', ascending=False)

   first  last                 email
0  Jacob    Xi   jacobxi@outlook.com
2   John  Wick  JohnWick@outlook.com
1   Jane   Doe  JaneDone@outlook.com
3   Mary   Doe        MD@outllok.com

In [13]:
df.sort_values(by=['last','first'], ascending=False)

   first  last                 email
0  Jacob    Xi   jacobxi@outlook.com
2   John  Wick  JohnWick@outlook.com
3   Mary   Doe        MD@outllok.com
1   Jane   Doe  JaneDone@outlook.com

In [14]:
df.sort_values(by=['last','first'], ascending=[False,True])

   first  last                 email
0  Jacob    Xi   jacobxi@outlook.com
2   John  Wick  JohnWick@outlook.com
1   Jane   Doe  JaneDone@outlook.com
3   Mary   Doe        MD@outllok.com

In [15]:
df.sort_index()

   first  last                 email
0  Jacob    Xi   jacobxi@outlook.com
1   Jane   Doe  JaneDone@outlook.com
2   John  Wick  JohnWick@outlook.com
3   Mary   Doe        MD@outllok.com

In [16]:
df['last'].sort_index()

0      Xi
1     Doe
2    Wick
3     Doe
Name: last, dtype: object

In [17]:
import pandas as pd
df = pd.read_csv('data/survey_results_public.csv')

In [18]:
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [19]:
df.sort_values('Country',inplace=True)

In [21]:
df['Country'].head(20)

39018    Afghanistan
62723    Afghanistan
85185    Afghanistan
50437    Afghanistan
88340    Afghanistan
88735    Afghanistan
6391     Afghanistan
39754    Afghanistan
88181    Afghanistan
48122    Afghanistan
10697    Afghanistan
62124    Afghanistan
49377    Afghanistan
32971    Afghanistan
60559    Afghanistan
85827    Afghanistan
88033    Afghanistan
28470    Afghanistan
719      Afghanistan
26189    Afghanistan
Name: Country, dtype: object

In [23]:
df.sort_values(by=['Country','ConvertedComp'],ascending=[True, False], inplace=True)

In [24]:
df[['Country','ConvertedComp']].head(20)

           Country  ConvertedComp
62723  Afghanistan      1000000.0
50172  Afghanistan       153216.0
39018  Afghanistan        19152.0
58082  Afghanistan        17556.0
7056   Afghanistan        14364.0
22327  Afghanistan         7980.0
48122  Afghanistan         4464.0
10697  Afghanistan         3996.0
8112   Afghanistan         1596.0
29560  Afghanistan         1116.0
28470  Afghanistan            0.0
719    Afghanistan            0.0
85185  Afghanistan            NaN
50437  Afghanistan            NaN
88340  Afghanistan            NaN
88735  Afghanistan            NaN
6391   Afghanistan            NaN
39754  Afghanistan            NaN
88181  Afghanistan            NaN
62124  Afghanistan            NaN

In [25]:
df['ConvertedComp'].nlargest(10)

25833    2000000.0
87353    2000000.0
21895    2000000.0
28080    2000000.0
72274    2000000.0
77665    2000000.0
79701    2000000.0
51798    2000000.0
75088    2000000.0
32056    2000000.0
Name: ConvertedComp, dtype: float64

In [29]:
df.nlargest(10, 'ConvertedComp')

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
25833,25983,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,24.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
87353,87896,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,32.0,Man,No,Gay or Lesbian,White or of European descent,No,Appropriate in length,Neither easy nor difficult
21895,22013,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,No,"Professional degree (JD, MD, etc.)","A natural science (ex. biology, chemistry, phy...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Easy
28080,28243,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,A lot less welcome now than last year,Tech meetups or events in your area,NaN,NaN,NaN,Straight / Heterosexual,NaN,Yes,Too short,Easy
72274,72732,"I am not primarily a developer, but I write co...",No,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",NaN,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,A lot less welcome now than last year,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,Yes,Too long,Easy
77665,78151,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Mexico,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,32.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina,No,Appropriate in length,Easy
79701,80200,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Netherlands,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,NaN,Tech articles written by other developers,25.0,Woman,No,Bisexual,White or of European descent,No,Appropriate in length,Easy
51798,52132,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Peru,No,Some college/university study without earning ...,I never declared a major,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,48.0,Man,NaN,NaN,Black or of African descent;East Asian;Hispani...,Yes,Appropriate in length,Easy
75088,75561,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Singapore,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A humanities discipline (ex. literature, histo...",...,Just as welcome now as I felt last year,Tech meetups or events in your area,37.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
32056,32250,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Switzerland,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Industry news about technologies you're intere...,30.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy

In [30]:
df.nsmallest(10, 'ConvertedComp')

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
28470,28638,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Afghanistan,NaN,"Other doctoral degree (Ph.D, Ed.D., etc.)",I never declared a major,...,A lot less welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,NaN
719,722,I am a developer by profession,No,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,NaN,Afghanistan,NaN,NaN,NaN,...,Not applicable - I did not use Stack Overflow ...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,Too long,Difficult
13760,13825,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,NaN,Algeria,NaN,NaN,NaN,...,A lot less welcome now than last year,NaN,56.0,NaN,NaN,NaN,NaN,Yes,Too short,Easy
40655,40913,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Armenia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers,22.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Easy
30447,30630,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,A lot less welcome now than last year,NaN,43.0,NaN,No,NaN,NaN,No,Appropriate in length,Easy
68611,69049,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,34.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
19235,19340,"I am not primarily a developer, but I write co...",Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",NaN,Austria,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Fine arts or performing arts (ex. graphic desi...,...,Just as welcome now as I felt last year,NaN,32.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
16126,16214,"I am not primarily a developer, but I write co...",Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Bangladesh,"Yes, part-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","A natural science (ex. biology, chemistry, phy...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,99.0,NaN,No,NaN,NaN,NaN,Too long,Easy
29184,29355,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...","Independent contractor, freelancer, or self-em...",Bosnia and Herzegovina,"Yes, part-time",Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,NaN,No,NaN,NaN,NaN,Too long,Easy
1678,1685,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Brazil,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Neither easy nor difficult